[project]
name = "courses"
version = "0.1.0"
description = "Your average courses platform"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bleach>=6.2.0",
    "flask>=3.1.2",
    "markdown>=3.9",
    "python-dotenv>=1.1.1",
]
