CREATE TABLE IF NOT EXISTS user (
  userid INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS course (
  courseid INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  desc TEXT NOT NULL,
  owner INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(owner) REFERENCES user(userid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS lesson (
  lessonid INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  owner INTEGER NOT NULL,
  course INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(owner) REFERENCES user(userid) ON DELETE CASCADE,
  FOREIGN KEY(course) REFERENCES course(courseid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS session (
  sessionid INTEGER PRIMARY KEY AUTOINCREMENT,
  useragent TEXT NOT NULL,
  user INTEGER NOT NULL,
  CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(user) REFERENCES user(userid) ON DELETE CASCADE
);
